---
- hosts: nodes

  vars: 
    packages:
      - npm
      - git
      - nodejs-legacy

  tasks: 
    - name: Install nodeJS
      apt: pkg={{packages}} state=present update_cache=yes
      become: yes

    - name: Install Forever
      npm: name=forever global=yes state=latest

    - name: Clone repo
      git:
        repo: https://github.com/CSC-DevOps/App.git
        dest: /home/vagrant/Homework/App

    - name: Install NPM packages
      command: npm install 
      args: 
        chdir: /home/vagrant/Homework/App/
      become: yes

    - name: Start main.js app using forever on port 9501
      command: forever start main.js 9501 
      args: 
        chdir: /home/vagrant/Homework/App/
      become: yes

    - name: Bash version check and update
      apt: name=bash state=latest
      become: yes

    - name: openssl version check and update
      apt: name=openssl state=latest
      become: yes

    - name: openssh-client version check and update
      apt: name=openssh-client state=latest
      become: yes

    - name: openssh-server version check and update
      apt: name=openssh-server state=latest
      become: yes
      
    - name: Remove everything in tmp directory
      file: 
        path: /temp/ 
        state: absent
      become: yes

    # emit a debug message with each package
    - debug:
        msg: "{{ item }}"
      with_items: "{{packages}}"

    # Combine the two commands to install a list of packages